# add_newline = true
palette = 'nord'
command_timeout = 200

# format = "[$directory$git_branch$git_status]($style)$character"

# removed $fill\ and $line_break\ from format
format = "$directory$git_branch$git_status$jobs$cmd_duration$character"
# format = """ 
# $directory\
# $git_branch\
# $git_status\
# $jobs\
# $cmd_duration\
# $character"""

[fill]
symbol = ' '

[character]
error_symbol = "[✗](bold cyan)"
success_symbol = "[❯](bold cyan)"


[directory]
truncation_length = 3
truncation_symbol = "…/"
repo_root_style = "bold cyan"
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "


[git_branch]
style = 'green'
symbol = ' '
format = '[on](white) [$symbol$branch ]($style)'
# format = "[$branch]($style) "
# style = "italic cyan"

[git_status]
format     = '[$all_status]($style)'
style      = "yellow"
ahead      = "⇡${count} "
diverged   = "⇕⇡${ahead_count}⇣${behind_count} "
behind     = "⇣${count} "
conflicted = " "
up_to_date = " "
untracked  = "? "
modified   = " "
stashed    = ""
staged     = ""
renamed    = ""
deleted    = ""


[palettes.nord]
dark_blue = '#5E81AC'
blue = '#81A1C1'
teal = '#88C0D0'
red = '#BF616A'
orange = '#D08770'
# green = '#A3BE8C'
green = '#9FD78A'
yellow = '#EBCB8B'
purple = '#B48EAD'
gray = '#434C5E'
black = '#2E3440'
white='#D8DEE9'

[palettes.onedark]
dark_blue='#61afef'
blue='#56b6c2'
red='#e06c75'
green='#98c379'
purple='#c678dd'
cyan='#56b6c2'
orange='#be5046'
yellow='#e5c07b'
gray='#828997'
white ='#abb2bf'
black='#2c323c'
